"""initial

Revision ID: 01a81fc78b67
Revises: 
Create Date: 2026-04-21 10:20:05.849766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a81fc78b67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Accounts_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('mobnum', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'DRIVER', name='role'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('mobnum')
    )
    op.create_table('Driver_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('govt_id', sa.String(length=50), nullable=True),
    sa.Column('Vechile_Number', sa.String(length=50), nullable=True),
    sa.Column('Vechile_type', sa.Enum('ELECTRIC', 'NORMAL', name='vechile_type'), nullable=True),
    sa.Column('verification', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verification'), nullable=True),
    sa.Column('ver_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['Accounts_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Vechile_Number'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('porter_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'COLLECTED', 'STARTED', 'REACHED', 'DROPPED', 'CANCELLED', 'USER_CANCELLED', name='status'), nullable=True),
    sa.Column('pickup_loc', sa.String(length=50), nullable=True),
    sa.Column('drop_loc', sa.String(length=50), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('reached_at', sa.DateTime(), nullable=True),
    sa.Column('dropped_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('user_cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['Driver_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Accounts_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('porter_table')
    op.drop_table('Driver_table')
    op.drop_table('Accounts_table')
    # ### end Alembic commands ###
