"""adding lat and long for souce and destination

Revision ID: 473ccc17cfb8
Revises: 01a81fc78b67
Create Date: 2026-04-27 21:54:54.410600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '473ccc17cfb8'
down_revision: Union[str, Sequence[str], None] = '01a81fc78b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Accounts_table', ['id'])
    op.create_unique_constraint(None, 'Driver_table', ['id'])
    op.add_column('porter_table', sa.Column('pickup_loc_long', sa.Float(), nullable=True))
    op.add_column('porter_table', sa.Column('pickup_loc_lat', sa.Float(), nullable=True))
    op.add_column('porter_table', sa.Column('drop_loc_long', sa.Float(), nullable=True))
    op.add_column('porter_table', sa.Column('drop_loc_lat', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('porter_table', 'drop_loc_lat')
    op.drop_column('porter_table', 'drop_loc_long')
    op.drop_column('porter_table', 'pickup_loc_lat')
    op.drop_column('porter_table', 'pickup_loc_long')
    op.drop_constraint(None, 'Driver_table', type_='unique')
    op.drop_constraint(None, 'Accounts_table', type_='unique')
    # ### end Alembic commands ###
